version: "3.9"

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - auth-service
      - users-service
      - posts-service   # ✅ added
    networks:
      - linkedin-network

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth/.env.docker
    volumes:
      - ./auth:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - linkedin-network

  users-service:
    build: ./users
    container_name: users-service
    ports:
      - "3002:3002"
    env_file:
      - ./users/.env.docker
    volumes:
      - ./users:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - linkedin-network

  posts-service:
    build: ./posts
    container_name: posts-service
    ports:
      - "3003:3003"
    env_file:
      - ./posts/.env.docker
    volumes:
      - ./posts:/app
      - /app/node_modules
      - ./posts/uploads:/app/uploads
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - linkedin-network

  postgres:
    image: postgres:15
    container_name: linkedin-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin_users   
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkedin-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: linkedin-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - linkedin-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: linkedin-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - linkedin-network

networks:
  linkedin-network:

volumes:
  postgres_data: